backend:
name: github
branch: master
repo: drood87/gatsby-test-repo

media_folder: static/img
public_folder: /img

collection:
  -name: 'team'
  label: 'Team'
folder: 'src/team'
create: true
slug: { { slug } }
fields:
  - { label: 'Team Member', name: 'title', widget: 'string' }
  - { label: 'Bio', name: 'bio', widget: 'markdown' }
